config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "pages#home"

  # GET localhost:3000/about
  get "/about", to: "pages#about"

  get "/contact", to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
    @members = ["Claire", "Toni", "Santi", "Sarah"]
    search = params[:member]
    if search
      @members = @members.select do |member|
        member == search
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Our First Rails App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>

<p>We are awesome</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>

<h2>Who do you want to contact?</h2>

<form action="/contact" method="get">
  <label for="member">Please type a name...</label>
  <input id="member" name="member" type="text" placeholder="Charlie">
  <input type="submit">
</form>

<ol>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

<p>We like receiving emails</p>

<%= link_to "Go back home", root_path %>

app/views/pages/home.html.erb
<h1>Welcome Home</h1>

<%= link_to "Contact Us", contact_path %>